# Generated by Django 4.2.4 on 2023-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_account_materials_provided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='materials_provided',
            field=models.CharField(choices=[(' debit card', 'Debit Card'), (' credit card', 'Credit Card'), (' cheque book', 'Cheque Book')], default=False, max_length=25),
        ),
    ]
