# Generated by Django 4.2.4 on 2023-08-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_account_materials_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='materials_provided',
            field=models.CharField(choices=[('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('cheque_book', 'Cheque Book')], max_length=25),
        ),
    ]
