# Generated by Django 4.2.4 on 2023-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_account_materials_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
