# Generated by Django 4.2.4 on 2023-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_account_age_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(),
        ),
    ]
